/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'receivedAmount' : IDL.Float64,
  'investAmount' : IDL.Float64,
});
export const Summary = IDL.Record({
  'totalReceived' : IDL.Float64,
  'averageDailyProfitPercentage' : IDL.Float64,
  'totalInvest' : IDL.Float64,
  'totalProfit' : IDL.Float64,
  'profitPercentage' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [Entry], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getSummary' : IDL.Func([], [Summary], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'receivedAmount' : IDL.Float64,
    'investAmount' : IDL.Float64,
  });
  const Summary = IDL.Record({
    'totalReceived' : IDL.Float64,
    'averageDailyProfitPercentage' : IDL.Float64,
    'totalInvest' : IDL.Float64,
    'totalProfit' : IDL.Float64,
    'profitPercentage' : IDL.Float64,
  });
  
  return IDL.Service({
    'addEntry' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [Entry], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getSummary' : IDL.Func([], [Summary], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };