/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DateString = IDL.Text;
export const EntryId = IDL.Nat;
export const Entry = IDL.Record({
  'id' : EntryId,
  'date' : DateString,
  'createdAt' : IDL.Int,
  'receivedAmount' : IDL.Float64,
  'investAmount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'lastLoginAt' : IDL.Opt(IDL.Int),
  'createdAt' : IDL.Int,
  'email' : IDL.Opt(IDL.Text),
  'passwordHash' : IDL.Opt(IDL.Text),
});
export const DashboardStats = IDL.Record({
  'totalReceived' : IDL.Float64,
  'totalInvested' : IDL.Float64,
  'totalProfit' : IDL.Float64,
  'avgDailyProfit' : IDL.Float64,
  'profitPercent' : IDL.Float64,
});
export const YearMonthString = IDL.Text;
export const MonthlySummary = IDL.Record({
  'totalReceived' : IDL.Float64,
  'totalInvested' : IDL.Float64,
  'entryCount' : IDL.Nat,
  'yearMonth' : YearMonthString,
  'totalProfit' : IDL.Float64,
  'avgDailyProfit' : IDL.Float64,
  'profitPercent' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntry' : IDL.Func([DateString, IDL.Float64, IDL.Float64], [Entry], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEntry' : IDL.Func([EntryId], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getMonthlySummaries' : IDL.Func([], [IDL.Vec(MonthlySummary)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'registerUserWithEmailPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'verifyEmailPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DateString = IDL.Text;
  const EntryId = IDL.Nat;
  const Entry = IDL.Record({
    'id' : EntryId,
    'date' : DateString,
    'createdAt' : IDL.Int,
    'receivedAmount' : IDL.Float64,
    'investAmount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'lastLoginAt' : IDL.Opt(IDL.Int),
    'createdAt' : IDL.Int,
    'email' : IDL.Opt(IDL.Text),
    'passwordHash' : IDL.Opt(IDL.Text),
  });
  const DashboardStats = IDL.Record({
    'totalReceived' : IDL.Float64,
    'totalInvested' : IDL.Float64,
    'totalProfit' : IDL.Float64,
    'avgDailyProfit' : IDL.Float64,
    'profitPercent' : IDL.Float64,
  });
  const YearMonthString = IDL.Text;
  const MonthlySummary = IDL.Record({
    'totalReceived' : IDL.Float64,
    'totalInvested' : IDL.Float64,
    'entryCount' : IDL.Nat,
    'yearMonth' : YearMonthString,
    'totalProfit' : IDL.Float64,
    'avgDailyProfit' : IDL.Float64,
    'profitPercent' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntry' : IDL.Func([DateString, IDL.Float64, IDL.Float64], [Entry], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEntry' : IDL.Func([EntryId], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getMonthlySummaries' : IDL.Func([], [IDL.Vec(MonthlySummary)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'registerUserWithEmailPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'verifyEmailPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };